# .github/workflows/build.yml

name: CI Build pingsweep

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths: # Only run if relevant files change
      - 'pingsweep.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
  pull_request:
    branches:
      - main # Also trigger on pull requests targeting main
    paths: # Only run if relevant files change
      - 'pingsweep.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'

jobs:
  build:
    # Use a matrix strategy to build for multiple OS/architectures
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goarch: [amd64] # You can add arm64 here if needed for specific OS
      fail-fast: false # Don't stop other builds if one fails

    runs-on: ${{ matrix.os }}

    steps:
      # Action to check out your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Action to set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          # Set GOARCH based on the matrix for cross-compilation if needed,
          # though 'runs-on' usually handles the primary architecture.
          # For explicit cross-compilation, you'd set GOOS and GOARCH env vars.

      # Ensures go.mod and go.sum are up-to-date and downloads dependencies
      - name: Go Mod Tidy
        run: go mod tidy

      # Build pingsweep binary for the current OS/architecture
      - name: Build pingsweep binary
        run: go build -o pingsweep-${{ runner.os }}-${{ matrix.goarch }} pingsweep.go
        # For Windows, the executable will automatically get a .exe extension.
        # For Linux/macOS, it won't.

      # Upload the built binary as a workflow artifact
      - name: Upload pingsweep binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pingsweep-${{ runner.os }}-${{ matrix.goarch }}
          path: pingsweep-${{ runner.os }}-${{ matrix.goarch }}${{ runner.os == 'Windows' && '.exe' || '' }}
          # How long to keep the artifact (optional)
          retention-days: 5 # Set artifact retention to 5 days
